"""
Django settings for suorganizer project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/
SITE_ID = 1
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#__lg$+^9ublw$^c))gyqvs1q8^4qjfaj560pix9=q^3n%b+@z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

INTERNAL_IPS = ['127.0.0.1',]


# Application definition

INSTALLED_APPS = [
    'user',   
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'django_extensions',
    'core',
    'organizer',
    'blog',    
    'contact',
    'debug_toolbar',    
    ]

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',   
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'suorganizer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',            
            ],
            'loaders': [
                    #('django.template.loaders.cached.Loader',[
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                     #]),
            ],
        },
    },
]

WSGI_APPLICATION = 'suorganizer.wsgi.application'

# Caches
# https://docs.djangoproject.com/en/1.11/topics/cache/#django-s-cache-framework

CACHES = {
        'default': {
                'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
                'LOCATION': 'unique-snowflake',
                'TIMEOUT': 600, #seconds == 10 mins
                }
        }
CACHE_MIDDLEWARE_ALIAS = 'default'
# User
#https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = 'user.User'
'''
This dotted pair describes the name of the Django app 
(which must be in your INSTALLED_APPS), 
and the name of the Django model that 
you wish to use as your User model.
'''

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Logging
# https://docs.djangoproject.com/en/1.8/topics/logging/
from django.core.urlresolvers import reverse_lazy

LOGIN_REDIRECT_URL = reverse_lazy('blog_post_list')
LOGIN_URL = reverse_lazy('dj-auth:login')
LOGOUT_URL = reverse_lazy('dj-auth:logout')

from .log_filters import ManagementFilter

verbose = (
        "[%(asctime)s] %(levelname)s"
        "[%(name)s:%(lineno)s]%(message)s"
        )

LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'filters' : {
                'remove_migration_sql': {
                    '()': ManagementFilter,},
                },
        'handlers': { 
                'console': {
                        'filters': ['remove_migration_sql'],
                        'class': 'logging.StreamHandler',
                },
        },
        'formatters': {
                'verbose':{
                        'format': verbose,
                        'datefmt': "%Y-%b-%d %H:%M:%S"
                },
        },
        'loggers':{
                'django': {
                        'handlers': ['console'],
                        'level': 'DEBUG',
                        'formatter': 'verbose',
                },
        },
 }


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = (
        ('en', 'English'),
        ('zh-hant', 'Traditional Chinese'),)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Fixtures
# https://docs.djangoproject.com/en/1.8/topics/serialization/

FIXTURE_DIRS = (os.path.join(BASE_DIR, 'fixtures'),)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
SERVER_EMAIL = '495100061dick@gmail.com'
DEFAULT_FROM_EMAIL = 'no-reply@django-unleashed.com'
EMAIL_SUBJECT_PREFIX = '[Startup Organizer]'
MANAGERS = ('Us', 'ourselves@django-unleashed.com')

