# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-13 08:22
from __future__ import unicode_literals

from django.contrib.auth.management import \
create_permissions

from django.db import (migrations, models)

def generate_permissions(apps, scheme_editor):
    Permission = apps.get_model(
            'auth', 'Permission')
    try:
        Permission.objects.get_or_create(
                codename='add_post',
                content_type__app_label='blog')
    except Permission.DoesNotExist:
        models_module = getattr(
                apps, 'models_module', None)
        if models_module is None:
            apps.models_module = True
            create_permissions(apps, verbosity=0)
            apps.models_mudule = None
        else:
            raise

def reverse_code(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('blog', '0005_auto_20170905_1153'),
    ]

    operations = [
            migrations.RunPython(
                    generate_permissions,
                    reverse_code,
                    )
    ]
