# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_newslink_slug'),
    ]

    operations = [
    ]
