# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_startup_tag_field_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslink',
            name='link',
            field=models.URLField(max_length=255, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='newslink',
            name='title',
            field=models.CharField(max_length=63, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='contact',
            field=models.EmailField(max_length=254, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=31, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='tags',
            field=models.ManyToManyField(blank=True, to='organizer.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='website',
            field=models.URLField(max_length=255, verbose_name='web site'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=31, verbose_name='name'),
        ),
    ]
