# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-24 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_auto_20170526_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslink',
            name='slug',
            field=models.SlugField(default='', max_length=63),
        ),
    ]
